# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Lopatin
author: Alexander Lopatin
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title/
url: "https://alopatindev.github.io" # the base hostname & protocol for your site
github_username: alopatindev
facebook_username: alopatindev
linkedin_username: AlexanderLopatin
disqus_shortname: alopatindev
rss: true

# Build settings
markdown: kramdown
timezone: Europe/Moscow
